package com.social.app.service.factory;

import com.social.app.data.entities.User;
import org.springframework.stereotype.Component;

/**
 * Provides methods for creating user entities.
 */
public interface UserFactory {

    /**
     * Creates a user with autogenerated id and username.
     * @param username username
     * @return user
     */
    User createUser(String username);

}
